### ISSUE TITLE
Suggestion: Level modification management

### ISSUE THREAD

**Issue by NeonPixels** [BrandenEK/Blasphemous.Framework.Levels#7]
Currently, the level modifications are parsed as long as they are present in the mod's levels folder.
This has two side effects I find concerning:

---

**First scenario:**
Our mod for this scenario only does one thing: Adds an item somewhere in the game world.
Let's say I decide to place it in Albero. I would then publish an update to the mod including the json file with said item.
But if on a later release I decide to move the item elsewhere, I would then rename the json file to match the area name of the new location.

But from a player perspective, they would download the new release, unzip the contents into their Modding folder... And now they would have two locations for the same item, as the old json file would not have been removed.

**Second scenario:**
As soon as people realize how this works, users would be able to freely edit/rename the json files, or even introduce their own json files, altering the mod operation.

----

Now, regarding the second scenario, that's user tampering, and maybe we don't need to worry about it, if they complain that their mod is broken, it's up to them.

But regarding the first, it can be an issue. My suggestion would be to be able to register map modifications in the same way we register penitences, so the mod only concerns itself with the json files it expects to find.
This would mean the mod would ignore json files it doesn't expect, and it would issue error messages for json files that are missing.

Just a suggestion.

**Comment by BrandenEK** [comment]
First scenario:
Updating or uninstalling a mod through the mod installer will remove all level files.  I doubt anyone is still manually installing mods, so this should cover most cases, but it wouldn't hurt to add a note about removing old files before updating.  I have thought about registering level edits through the service provider, but decided against it since for mods with a huge amount of levels (Screaming Sinners) that would be not good.  It would also require recompiling the mod when someone adds a new level edit, which is not ideal for community projects with designers who are unfamiliar about coding.

Second scenario:
I am completely fine with this.  All image, localization, and data files are also freely accessible to users.  They can change them if they want.  They probably shouldn't, but all these mods are open-source anyways so I'm not encrypting or hiding the data anywhere.
